docs: fix link redirection and add missing sestions on readme

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,22 +1,17 @@
-#!/usr/bin/env sh
-. "$(dirname "$0")/_/husky.sh"
-
 pnpm run prettier:write
 pnpm run eslint
+
 echo "Running pre-commit hook"
 
-commands=("pnpm build"
-          "pnpm storybook:build"
-          )
+run_command() {
+  echo "Running: $1"
+  sh -c "$1" || {
+    echo "Command failed: $1"
+    exit 1
+  }
+}
 
-for cmd in "${commands[@]}"; do
-    echo "Running: $cmd"
-    $cmd || {
-        echo "Command failed: $cmd"
-        exit 1
-    }
-done
+run_command "pnpm build"
+run_command "pnpm storybook:build"
 
-echo "All pre-commmit checks passed!"
-
-
+echo "All pre-commit checks passed!"
